version: 2
updates:
  - package-ecosystem: 'bundler'
      directory: "/Formula"
    schedule:
      interval: "weekly"
      time: "09:00"
      day: "monday"
      timezone: "America/Inuvik"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "09:00"
      day: "monday"
      timezone: "America/Inuvik"
